source 'https://rubygems.org'

gem 'httparty'
gem 'exception_notification'
gem 'slack-notifier'
gem 'figaro'
gem 'mail'
gem 'font-awesome-sass'
gem 'aasm'
gem 'omniauth'
gem 'omniauth-github'
gem 'http_accept_language'
gem 'kaminari'
gem 'globalize'
gem 'sitemap_generator'
gem 'rest-client'
gem 'bing_translator'
gem 'friendly_id'
gem 'colorize'
gem 'devise'
gem 'rails', '4.2.0'
gem 'mysql'
gem 'mysql2', '~> 0.3.18'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
group :development do
  gem 'capistrano-rails'
  gem 'capistrano-passenger'
  gem 'sshkit-sudo'
  gem 'seed_dump'
end
group :development, :test do
  gem 'pry'
  gem 'pry-rails'
  gem 'pry-nav'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'rspec-rails'
  gem 'capybara'
  gem 'factory_girl_rails'
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
gem 'redcarpet'
gem 'coderay'
